### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by yachty66** [kossLAN/DiscordChatBot#1]
'instruction_template': 'None', #I'm really not sure why we have instruction templates now...

... because of the greeting?

**Comment by kossLAN** [comment]
I mean I didn't research what it did, because I had to patch bot from earlier iteration that did not have it, just put my thoughts in the from of a comment lol.

**Comment by yachty66** [comment]
you define "context = (f'{char_persona}\n<START>\n{example_dialogue}\n')" but its never used again. but context is usually defined in the templates.

havnt found a workaround yet how to use custom context together with api.

**Comment by kossLAN** [comment]
I don't have really interest in maintaining this, if you have any solutions ill accept if it works/isn't malware.

**Comment by kossLAN** [comment]
Alternatively fork it.
